"use client";
import { useEffect, useState } from "react";
type Item = { id: number; recipient_label?: string; destination_masked?: string; message_text?: string; attachment_names: string[]; sent_at: string; expires_at?: string | null; campaigns?: { name?: string } | null; confirmation?: { confirmed_at?: string | null; expires_at: string } | null };
export function CommunicationLog({ groupId }: { groupId: string }) {
  const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); const response = await fetch(`/api/communication-log?groupId=${encodeURIComponent(groupId)}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) { setItems(body.items ?? []); setError(""); } else setError(body.error ?? "Falha ao carregar log"); setBusy(false); }
  useEffect(() => { void load(); const update = () => void load(); window.addEventListener("portal-refresh", update); return () => window.removeEventListener("portal-refresh", update); }, [groupId]);
  return <section className="panel" id="log-comunicacoes"><div className="panel-heading"><div><h2>Log de comunicacoes</h2><p>Texto e materiais enviados, destinatarios protegidos e confirmacoes de recebimento.</p></div><button className="small secondary" disabled={busy} onClick={load}>{busy ? "Atualizando..." : "Atualizar"}</button></div>{error && <div className="alert error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Campanha</th><th>Destinatario</th><th>Conteudo</th><th>Materiais</th><th>Envio</th><th>Confirmacao</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.campaigns?.name ?? "-"}</td><td>{item.recipient_label ?? "-"}<br/><span className="muted">{item.destination_masked ?? "Protegido"}</span></td><td className="message-preview">{item.message_text ?? "-"}</td><td>{item.attachment_names?.join(", ") || "Sem anexo"}</td><td>{new Date(item.sent_at).toLocaleString("pt-BR")}</td><td>{item.confirmation?.confirmed_at ? `Confirmada em ${new Date(item.confirmation.confirmed_at).toLocaleString("pt-BR")}` : item.confirmation ? "Aguardando" : "Nao solicitada"}</td></tr>)}</tbody></table></div>{!items.length && !error && <p className="empty">Nenhuma comunicacao registrada para este grupo.</p>}</section>;
}
