"use client";

import { FormEvent, useMemo, useState } from "react";

type Option = { id: string; name: string; group_id?: string };
type Summary = { campaigns: number; queue: number; sent: number; failures: number; canceled: number; communications: number; confirmations: number; inbound: number; audit: number };
const TYPES = [
  ["campaigns", "Campanhas"], ["queue", "Envios, sucessos e falhas"], ["communications", "Comunicacoes enviadas"],
  ["confirmations", "Confirmacoes de recebimento"], ["inbound", "Respostas e reacoes"], ["audit", "Auditoria"], ["accounts", "Contas do WhatsApp"],
] as const;

export function ReportsManager({ groups, campaigns, users }: { groups: Option[]; campaigns: Option[]; users: Option[] }) {
  const [filters, setFilters] = useState({ groupId: "", campaignId: "", actorId: "", status: "", dateFrom: "", dateTo: "" });
  const [types, setTypes] = useState<string[]>(TYPES.map(([key]) => key));
  const [summary, setSummary] = useState<Summary | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const visibleCampaigns = useMemo(() => filters.groupId ? campaigns.filter((item) => item.group_id === filters.groupId) : campaigns, [campaigns, filters.groupId]);
  function query(extra?: Record<string,string>) { const params = new URLSearchParams({ ...filters, ...extra }); for (const [key,value] of [...params.entries()]) if (!value) params.delete(key); return params.toString(); }
  async function consult(event?: FormEvent) { event?.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/reports?${query()}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error ?? "Nao foi possivel gerar o relatorio"); else setSummary(body.summary); } catch { setError("Falha de conexao ao consultar os relatorios"); } finally { setBusy(false); } }
  function exportExcel(all = false) { const selected = all ? TYPES.map(([key]) => key) : types; if (!selected.length) { setError("Selecione ao menos um tipo de relatorio para exportar."); return; } window.location.href = `/api/reports?${query({ format: "xlsx", types: selected.join(",") })}`; }
  return <>
    <section className="panel"><div className="panel-heading"><div><h2>Filtros dos relatorios</h2><p>Combine projeto, campanha, periodo, status e usuario. Os filtros tambem valem para o arquivo Excel.</p></div></div><form className="stack" onSubmit={consult}><div className="form-grid"><label>Projeto ou grupo<select value={filters.groupId} onChange={(event) => setFilters((current) => ({ ...current, groupId:event.target.value, campaignId:"" }))}><option value="">Todos permitidos</option>{groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Campanha<select value={filters.campaignId} onChange={(event) => setFilters((current) => ({ ...current, campaignId:event.target.value }))}><option value="">Todas</option>{visibleCampaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Data inicial<input type="date" value={filters.dateFrom} onChange={(event) => setFilters((current) => ({ ...current, dateFrom:event.target.value }))}/></label><label>Data final<input type="date" value={filters.dateTo} onChange={(event) => setFilters((current) => ({ ...current, dateTo:event.target.value }))}/></label><label>Status do envio<select value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status:event.target.value }))}><option value="">Todos</option><option value="enviado">Enviado com sucesso</option><option value="erro">Falha</option><option value="processando">Em andamento</option><option value="pronto_para_envio">Pronto</option><option value="pendente">Pendente</option><option value="cancelado">Cancelado</option></select></label><label>Usuario na auditoria<select value={filters.actorId} onChange={(event) => setFilters((current) => ({ ...current, actorId:event.target.value }))}><option value="">Todos</option>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><button disabled={busy}>{busy ? "Consultando..." : "Aplicar filtros"}</button></form>{error && <div className="alert error" role="alert">{error}</div>}</section>
    {summary && <section className="panel"><div className="panel-heading"><div><h2>Resumo encontrado</h2><p>Totais correspondentes aos filtros selecionados.</p></div></div><div className="summary-grid report-summary"><strong>{summary.campaigns} campanhas</strong><strong>{summary.queue} itens na fila</strong><strong>{summary.sent} sucessos</strong><strong>{summary.failures} falhas</strong><strong>{summary.canceled} cancelados</strong><strong>{summary.confirmations} confirmacoes</strong><strong>{summary.inbound} retornos</strong><strong>{summary.audit} atividades</strong></div></section>}
    <section className="panel"><div className="panel-heading"><div><h2>Exportar para Excel</h2><p>Escolha planilhas individuais ou gere um unico arquivo com todas as abas.</p></div></div><div className="report-type-grid">{TYPES.map(([key,label]) => <label className="check" key={key}><input type="checkbox" checked={types.includes(key)} onChange={(event) => setTypes((current) => event.target.checked ? [...current,key] : current.filter((item) => item !== key))}/>{label}</label>)}</div><div className="actions"><button type="button" onClick={() => exportExcel(false)}>Exportar selecionados</button><button type="button" className="secondary" onClick={() => exportExcel(true)}>Exportar tudo em um arquivo</button></div><p className="muted">Telefones de destinatarios permanecem protegidos. O arquivo inclui apenas os dados que seu perfil pode consultar.</p></section>
  </>;
}
