"use client";
import { FormEvent, useEffect, useState } from "react";

type Settings = { retention_days: number; delay_min_seconds: number; delay_max_seconds: number; batch_size: number; batch_pause_minutes: number; account_rotation_batch_size: number };
export function SettingsManager({ canEdit }: { canEdit: boolean }) {
  const [settings, setSettings] = useState<Settings | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch("/api/settings").then((response) => response.json()).then((body) => setSettings(body.settings ?? null)); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ retentionDays: data.get("retentionDays"), delayMin: data.get("delayMin"), delayMax: data.get("delayMax"), batchSize: data.get("batchSize"), batchPause: data.get("batchPause"), accountRotationBatchSize: data.get("accountRotationBatchSize") }) }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? "Configuracoes salvas" : body.error ?? "Falha ao salvar"); setBusy(false); }
  if (!settings) return <section className="panel"><p>Carregando configuracoes...</p></section>;
  return <section className="panel" id="configuracoes"><div className="panel-heading"><div><h2>Regras de envio e privacidade</h2><p>Preferencias aplicadas às novas campanhas. Zero dias mantém o histórico sem expiração.</p></div></div><form className="stack" onSubmit={save}><div className="form-grid"><label>Retencao do log em dias<input name="retentionDays" type="number" min="0" max="3650" defaultValue={settings.retention_days} disabled={!canEdit} /></label><label>Delay minimo em segundos<input name="delayMin" type="number" min="0" max="3600" defaultValue={settings.delay_min_seconds} disabled={!canEdit} /></label><label>Delay maximo em segundos<input name="delayMax" type="number" min="0" max="3600" defaultValue={settings.delay_max_seconds} disabled={!canEdit} /></label><label>Tamanho do lote<input name="batchSize" type="number" min="1" max="500" defaultValue={settings.batch_size} disabled={!canEdit} /></label><label>Pausa entre lotes em minutos<input name="batchPause" type="number" min="0" max="1440" defaultValue={settings.batch_pause_minutes} disabled={!canEdit} /></label><label>Alternar conta a cada quantas mensagens<input name="accountRotationBatchSize" type="number" min="1" max="500" defaultValue={settings.account_rotation_batch_size} disabled={!canEdit} /><small>Exemplo: 10 envia dez mensagens por uma conta antes de passar para a proxima.</small></label><label>Fuso horario<input value="America/Sao_Paulo" disabled /></label></div>{canEdit && <button disabled={busy}>{busy ? "Salvando..." : "Salvar configuracoes"}</button>}</form>{message && <p className="action-message">{message}</p>}<div className="alert warning"><strong>Atencao:</strong> campanhas acima de 250 mensagens aumentam o risco de bloqueio do numero. O portal recomendará lotes de 100 antes da liberação.</div></section>;
}
